name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "1,10,20,45 11 1,4,9,7,11,17,21,27 1-12 *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "hslibc77@gmail.com"
          git config --local user.name "ephmYZnq"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
